### ISSUE TITLE
[Failed] Action failing to convert Long README.

### ISSUE THREAD

**Issue by HarshalRathore** [dephraiim/translate-readme#7]
**Hello,** there first thank you for this awesome tool.

## What happened?
The action failed to convert the English version of Readme to all other versions except the first one in line which is the Chinese Simplified version.

## What do you think happened?
I think since the README file was pretty big only the first version in line got converted all others simply resulted in failure. 
readme file --> [Nerd font's README](https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md)
## What makes you so sure?
I tried it again but this time removed the Chinese simplified and traditional from workflow only left with Hindi French and Arabic in the respective order. The result was that only the Hindi version(first in line) was successful and french and Arabic failed,

I have also tried it with small README files and the Action was successful.

## Were you able to come up with any temporary/permanent solution?
The only temporary solution I was able to come up with is that creating separate YAML files for each conversion of the readme.
But it is not good as it creates a lot of unnecessary commits.

I Also tried putting timestamps between every job of 5min but that also did not work. 

## Logs
[Only Hindi was successful](https://github.com/HarshalRathore/Hello-World/runs/4431630580?check_suite_focus=truea)
[Log of the original workflow as copied from this repositories README](https://github.com/HarshalRathore/nerd-fonts/runs/4431872395?check_suite_focus=true)

**Comment by dephraiim** [comment]
Hello, could you please elaborate more?

**Comment by dephraiim** [comment]
@HarshalRathore 

I looked into more detail and since I am making a request the Google Translation API it is **limited to 5000 characters** and I think that is the reason why longer readme files are failiing.
